# config/_default/languages.en.toml

title = "Carlos Craveiro Personal Page"

[author]
name = "Carlos Henrique Craveiro Aquino Veras"
image = "img/author.jpg"
headline = "Robotics Researcher | M.Sc. Candidate at USP | UAVs & State Estimation"
bio = "M.Sc. Candidate in Aeronautics Engineering at USP and researcher at CRob. My work focuses on the intersection of Theoretical Robotics, State Estimation, and Embedded Systems, particularly applied to Unmanned Aerial Vehicles (UAVs)."
links = [
  { github = "https://github.com/CarlosCraveiro" },
  { linkedin = "https://www.linkedin.com/in/carloscraveiro/" },
  { link = "http://lattes.cnpq.br/4263198323019177" },
  { orcid = "https://orcid.org/0009-0001-2212-8860"}
]
email = "carlos.craveiro@usp.br"

[params]
logo = "white-carnage2_withoutbg.png"
