# config/_default/menus.en.toml

[[main]]
  name = "Blog Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

[[main]]
  identifier = "source_code"
  pre = "github"
  url = "https://github.com/CarlosCraveiro/personal_blog"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "GitHub"
  url = "https://github.com/CarlosCraveiro/personal_blog"
  weight = 40
