# Workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages usin Nix  

on:  
  push:    
    branches:      
      - main  
  workflow_dispatch:

permissions:  
  contents: read  
  pages: write  
  id-token: write

concurrency:  
  group: "pages"  
  cancel-in-progress: false

defaults:  
  run:    
    shell: bash

jobs:  
  # Build job  
  build:    
    runs-on: ubuntu-22.04    
    steps:       
      - name: Install Nix        
        uses: nixbuild/nix-quick-install-action@v21        
        with:          
          nix_conf: experimental-features = nix-command flakes      
      
      - name: Checkout        
        uses: actions/checkout@v4        
        with:          
          submodules: recursive          
          fetch-depth: 0      
      
      - name: Setup Pages        
        id: pages        
        uses: actions/configure-pages@v4      
      
      - name: Install Node.js dependencies        
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"          
      
      - name: Build site with Nix        
        run: nix build --print-build-logs      
      
      - name: Adjust permissions        
        run: |          
          chown -R `id -u`:`id -g` ./result          
          chmod -R a+rwx ./result       
      
      - name: Upload artifact        
        uses: actions/upload-pages-artifact@v3 
        with:          
          path: ./result  

  # Deployment job  
  deploy:    
    environment:      
      name: github-pages      
      url: ${{ steps.deployment.outputs.page_url }}    
    runs-on: ubuntu-22.04
    needs: build    
    steps:      
      - name: Deploy to GitHub Pages        
        id: deployment        
        uses: actions/deploy-pages@v4
